# Generated by Django 2.2.5 on 2021-07-07 07:48

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_auto_20210706_1644'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='reservation',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
