# Generated by Django 2.2.5 on 2021-07-11 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_auto_20210707_1648'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='reservation',
            managers=[
            ],
        ),
    ]
